language: ruby
cache: bundler
before_install:
- openssl aes-256-cbc -K $encrypted_3d22a8bf1dac_key -iv $encrypted_3d22a8bf1dac_iv
  -in .env.enc -out .env -d
install: bundle install --jobs=3 --retry=3 --path vendor/bundle
rvm:
- 2.6.2
- 2.5.5
- 2.4.6

script:
- bundle exec rake spec:unit

matrix:
  include:
    - name: "License check"
      rvm: 2.5.5
      script: bundle exec rake license_finder:check
    - name: "Help test"
      rvm: 2.5.5
      script: bundle exec 3scale help
    - name: "Integration Tests"
      rvm: 2.5.5
      script: bundle exec rake spec:integration
      if: type = cron
