language: ruby
cache: bundler
before_install:
- gem install bundler -v 1.15.1
rvm:
- 2.5.1
- 2.4.1
- 2.3.1
script:
  - bundle exec rake spec:all
  - bundle exec 3scale help
  - bundle exec 3scale help copy
  - bundle exec 3scale help import
