language: ruby
cache: bundler
before_install:
- gem install bundler -v 1.15.1
rvm:
- 2.4.1
- 2.3.1
- 2.2.5
- 2.1.9
script:
  - bundle exec rake spec:all
  - rake install
  - 3scale help
  - 3scale help copy
  - 3scale help import
