language: ruby
cache: bundler
before_install:
- gem install bundler -v 1.11.2
rvm:
- 2.3.0
- 2.2.4
- 2.1.8
- jruby-9.0.5.0
- rbx-3.19
matrix:
  allow_failures:
  - rvm: rbx-3.19
script:
- rake install
- 3scale help
