language: ruby
cache: bundler
before_install:
- openssl aes-256-cbc -K $encrypted_3d22a8bf1dac_key -iv $encrypted_3d22a8bf1dac_iv
  -in .env.enc -out .env -d
rvm:
- 2.6.2
- 2.5.5
- 2.4.6
script:
- bundle exec rake license_finder:check
- bundle exec rake spec:all
- bundle exec 3scale help
- bundle exec 3scale help copy
- bundle exec 3scale help import
