version: 2.1

commands:
  setup-bundler:
    steps:
      - run:
          name: setup bundler
          command: |
            sudo gem update --system
            sudo gem uninstall bundler
            sudo rm /usr/local/bin/bundle || true
            sudo rm /usr/local/bin/bundler || true
            sudo gem install bundler

  install_dependencies:
    steps:
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies

      - run:
          name: Install dependencies
          command: |
            bundle install --jobs=3 --retry=3 --path vendor/bundle

      - save_cache:
          key: v2-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle

  unittests:
    steps:
      - install_dependencies
      - run:
          name: Run unittests
          command: |
            bundle exec rake spec:unit

  setup-docker:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true

jobs:
  ruby-255-unittest:
    docker:
      - image: circleci/ruby:2.5.5
        environment:
          BUNDLER_VERSION: 2.1.4
    working_directory: ~/repo
    steps:
      - checkout
      - setup-bundler
      - unittests

  ruby-262-unittest:
    docker:
      - image: circleci/ruby:2.6.2
        environment:
          BUNDLER_VERSION: 2.1.4
    working_directory: ~/repo
    steps:
      - checkout
      - setup-bundler
      - unittests

  ruby-270-unittest:
    docker:
      - image: circleci/ruby:2.7.0
    working_directory: ~/repo
    steps:
      - checkout
      - unittests

  license_check:
    docker:
      - image: circleci/ruby:2.5.5
        environment:
          BUNDLER_VERSION: 2.1.4
    working_directory: ~/repo
    steps:
      - checkout
      - setup-bundler
      - install_dependencies
      - run:
          name: License check
          command: |
            bundle exec rake license_finder:check

  help_test:
    docker:
      - image: circleci/ruby:2.5.5
        environment:
          BUNDLER_VERSION: 2.1.4
    working_directory: ~/repo
    steps:
      - checkout
      - setup-bundler
      - install_dependencies
      - run:
          name: Help test
          command: |
            bundle exec 3scale help

  integration_tests:
    docker:
      - image: circleci/ruby:2.5.5
        environment:
          BUNDLER_VERSION: 2.1.4
    working_directory: ~/repo
    steps:
      - checkout
      - setup-bundler
      - install_dependencies
      - run:
          name: Integration Tests
          command: |
            bundle exec rake spec:integration

  docker_container_help_test:
    docker:
    - image: docker:stable
    steps:
      - setup-docker
      - run:
          name: Docker container help test
          command: |
            docker run --rm -t quay.io/redhat/3scale-toolbox:master 3scale help

workflows:
  version: 2
  basic_tests:
    jobs:
      - ruby-255-unittest
      - ruby-262-unittest
      - ruby-270-unittest
      - license_check
      - help_test

  integration:
    jobs:
      - manual_approval: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          # On approval of the `hold` job, any successive job that requires the `hold` job will run.
      - integration_tests:
          context: autotestaccount
          requires:
            - manual_approval
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - integration_tests:
          context: autotestaccount
      - docker_container_help_test
